Tokenline improvements
hydrabus/tokenline pull request #1
Opened 2019-09-25 14:54 UTC by 0x8008135

Hey,

This commit aims to fix some issues in tokenline which could happen when such command was sent to Hydrabus : 

> spi1> [0x3a 0x0f [0x3b r]
WRITE: 0x5B 0x30 0x78 0x33 0x61 
WRITE: 0x0F
WRITE: 0x5B 0x30 0x78 0x33 0x62 
WRITE: 0x72 0x5D

Because of the missing spaces, tokenline was unable to parse it correctly. With this patch :
>spi1> [0x3a 0x0f [0x3b r]
/CS ENABLED
WRITE: 0x3A 0x0F 
/CS ENABLED
WRITE: 0x3B
READ: 0xFF
/CS DISABLED

One of the good side effect happens when the user hit "Tab" execute the command and history up, the command will magically transform into: 
> [ 0x3a 0x0f [ 0x3b r ]

While debugging I found another bug with the ":" delimiter which was stripped from the CLI when hitting  "Tab"
> spi1> %:5 
   show           Show SPI parameters
   trigger        Setup SPI trigger
   device         SPI device (1/2)
   pull           GPIO pull (up/down/floating)
   mode           Mode (master/slave)
   frequency      Bus frequency
   polarity       Clock polarity (0/1)
   phase          Clock phase (0/1)
   msb-first      Send/receive MSB first
   lsb-first      Send/receive LSB first
   read           Read byte (repeat with :<num>)
   hd             Read byte (repeat with :<num>) and print hexdump
   write          Write byte (repeat with :<num>)
   <integer>      Write byte (repeat with :<num>)
   <string>       Write string
   cs-on          Alias for "chip-select on"
   cs-off         Alias for "chip-select off"
   [              Alias for "chip-select on"
   ]              Alias for "chip-select off"
   &              Delay 1 usec (repeat with :<num>)
   %              Delay 1 msec (repeat with :<num>)
   ~              Write a random byte (repeat with :<num>)
   exit           Exit SPI mode
spi1> % 5 

The reason was that the ":" delimiter was stripped during token identification and never put back.

Extensive testing has ben perfomed on this patch, but to prevent any further issues, please review/test before merging.

Cheers

2019-09-26 20:42 UTC, bvernoux commented
After lot of test (using peripheral **spi**) there is at least 2 bugs (from old code)
**BUG1 string starting with a number (from 0 to 9) fail and interpret it as decimal value**
```
"0" => Error recognised as 1 byte decimal (WRITE: 0x09 instead of WRITE: 0x30)
"9" => Error recognised as 1 byte decimal (WRITE: 0x09 instead of WRITE: 0x39)
"00" to "07" => Error recognised as 1 byte decimal (WRITE: 0x00 to WRITE: 0x07)
"08" => WRITE: 0x30 0x38 => OK
"09" => WRITE: 0x30 0x39 => OK
"99" => Error recognised as 1 byte decimal (WRITE: 0x63 instead of WRITE: 0x39 0x39)
"999" => Returns "Please specify one byte at a time."
```

BUG2 KO limit(128) (At max limit 128 but last char not take into account ...)
```
["abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ012345678"]
```
Obtained result:
```
spi1> ["abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ012345678"]
WRITE: 0x5B 0x20 0x22 0x61 0x62 0x63 0x64 0x65 0x66 0x67 0x68 0x69 0x6A 0x6B 0x6C 0x6D 0x6E 0x6F 0x70 0x71 0x72 0x73 0x74 0x75 0x76 0x77 0x78 0x79 0x7A 0x41 0x42 0x43 0x44 0x45 0x46 0x47 0x48 0x49 0x4A 0x4B 0x4C 0x4D 0x4E 0x4F 0x50 0x51 0x52 0x53 0x54 0x55 0x56 0x57 0x58 0x59 0x5A 0x30 0x31 0x32 0x33 0x34 0x35 0x36 0x37 0x38 0x39 0x61 0x62 0x63 0x64 0x65 0x66 0x67 0x68 0x69 0x6A 0x6B 0x6C 0x6D 0x6E 0x6F 0x70 0x71 0x72 0x73 0x74 0x75 0x76 0x77 0x78 0x79 0x7A 0x41 0x42 0x43 0x44 0x45 0x46 0x47 0x48 0x49 0x4A 0x4B 0x4C 0x4D 0x4E 0x4F 0x50 0x51 0x52 0x53 0x54 0x55 0x56 0x57 0x58 0x59 0x5A 0x30 0x31 0x32 0x33 0x34 0x35 0x36 0x37 0x38 0x22 0x5D 0x01
```
Expected result:
```
/CS ENABLED
WRITE: 0x61 0x62 0x63 0x64 0x65 0x66 0x67 0x68 0x69 0x6A 0x6B 0x6C 0x6D 0x6E 0x6F 0x70 0x71 0x72 0x73 0x74 0x75 0x76 0x77 0x78 0x79 0x7A 0x41 0x42 0x43 0x44 0x45 0x46 0x47 0x48 0x49 0x4A 0x4B 0x4C 0x4D 0x4E 0x4F 0x50 0x51 0x52 0x53 0x54 0x55 0x56 0x57 0x58 0x59 0x5A 0x30 0x31 0x32 0x33 0x34 0x35 0x36 0x37 0x38 0x39 0x61 0x62 0x63 0x64 0x65 0x66 0x67 0x68 0x69 0x6A 0x6B 0x6C 0x6D 0x6E 0x6F 0x70 0x71 0x72 0x73 0x74 0x75 0x76 0x77 0x78 0x79 0x7A 0x41 0x42 0x43 0x44 0x45 0x46 0x47 0x48 0x49 0x4A 0x4B 0x4C 0x4D 0x4E 0x4F 0x50 0x51 0x52 0x53 0x54 0x55 0x56 0x57 0x58 0x59 0x5A 0x30 0x31 0x32 0x33 0x34 0x35 0x36 0x37 0x38
/CS DISABLED
```



For other case I have a draft of different tests 
[test_tokenline.txt](https://github.com/hydrabus/tokenline/files/3659813/test_tokenline.txt)
(to be used later as non regression/validation test)

2019-09-30 12:37 UTC, 0x8008135 commented
Hello,

The latest commit should fix some of the issues.

Cheers

2019-09-30 18:57 UTC, Baldanos requested changes

2019-09-30 18:57 UTC, Baldanos commented on tokenline.c
> +							add_charz(tl, '\x20');
Should be add_charz(tl, ' ');

2019-09-30 18:57 UTC, Baldanos commented on tokenline.c
> +						add_charz(tl, '\x20');
Should be add_charz(tl, ' ');

2019-09-30 18:57 UTC, Baldanos commented on tokenline.c
> +static void add_charz(t_tokenline *tl, int c)
Function name is not self-explanatory.

Also, since it is similar to add_char(), should be placed just above or below the later.

2019-09-30 18:57 UTC, Baldanos commented on tokenline.c
> +				if(tl->buf[i+1] != '\x20' && tl->buf[i+1] != 0 && tl->buf[i+1] != ':' && i < tl->buf_len) {
Use ' ' instead of '\x20' for clarity

2019-09-30 18:57 UTC, Baldanos commented on tokenline.c
> +					if (tl->buf[i-1] != '\x20' && tl->buf[i-1] != 0 && tl->buf[i-1] != ':' && i < tl->buf_len){
Use ' ' instead of '\x20' for clarity

2019-09-30 18:58 UTC, Baldanos commented
Really good job.

Just needs some polish and to me it can be merged

2019-10-01 16:54 UTC, bvernoux commented
For information latest tokenline test in progress (to check limit cases ...)
[test_tokenline_30Sep19.txt](https://github.com/hydrabus/tokenline/files/3677619/test_tokenline_30Sep19.txt)

2019-10-01 22:17 UTC, Baldanos approved these changes

2019-10-03 18:18 UTC, merged

2019-10-03 18:19 UTC, Baldanos commented
Incredible work @0x8008135 thanks for your work

2019-10-03 20:02 UTC, bvernoux commented
Yes just one word AMAZING !!!